//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slamby.API.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TagResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal TagResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Slamby.API.Resources.TagResources", typeof(TagResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Duplicate Tag Id found: &apos;{0}&apos;.
        /// </summary>
        internal static string DuplicateIdsFound_0 {
            get {
                return ResourceManager.GetString("DuplicateIdsFound_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Export file can be download from here: {0}.
        /// </summary>
        internal static string ExportFileCanBeDownloadFromHere_0 {
            get {
                return ResourceManager.GetString("ExportFileCanBeDownloadFromHere_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Exporting words from {0} tag(s) of dataset {1}.
        /// </summary>
        internal static string ExportingWordsFrom_0_TagOfDataset_1 {
            get {
                return ResourceManager.GetString("ExportingWordsFrom_0_TagOfDataset_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No operation can be done on empty tag list.
        /// </summary>
        internal static string NoOperationCanBeDoneOnEmptyTagList {
            get {
                return ResourceManager.GetString("NoOperationCanBeDoneOnEmptyTagList", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ParentId &apos;{0}&apos; not found in Tag with Id &apos;{1}&apos;.
        /// </summary>
        internal static string ParentId_0_NotFoundInTagWithId_1 {
            get {
                return ResourceManager.GetString("ParentId_0_NotFoundInTagWithId_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Successfully exported words from {0} tag(s) of dataset {1}!.
        /// </summary>
        internal static string SuccessfullyExportedWordsFrom_0_TagsOfDataset_1 {
            get {
                return ResourceManager.GetString("SuccessfullyExportedWordsFrom_0_TagsOfDataset_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tag &apos;{0}&apos; is not a leaf element, provide force=true parameter in order to delete this tag..
        /// </summary>
        internal static string Tag_0_IsNotALeafElementProvideForceTrue {
            get {
                return ResourceManager.GetString("Tag_0_IsNotALeafElementProvideForceTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tag Id is empty.
        /// </summary>
        internal static string TagIdIsEmpty {
            get {
                return ResourceManager.GetString("TagIdIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tag Id should be integer type.
        /// </summary>
        internal static string TagIdShouldBeIntegerType {
            get {
                return ResourceManager.GetString("TagIdShouldBeIntegerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tag with Id &apos;{0}&apos; already exists.
        /// </summary>
        internal static string TagWithId_0_AlreadyExists {
            get {
                return ResourceManager.GetString("TagWithId_0_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tag with Id &apos;{0}&apos; does not found.
        /// </summary>
        internal static string TagWithId_0_DoesNotFound {
            get {
                return ResourceManager.GetString("TagWithId_0_DoesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tag with ParentId &apos;{0}&apos; does not found.
        /// </summary>
        internal static string TagWithParentId_0_DoesNotFound {
            get {
                return ResourceManager.GetString("TagWithParentId_0_DoesNotFound", resourceCulture);
            }
        }
    }
}
