//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slamby.API.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataSetResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal DataSetResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Slamby.API.Resources.DataSetResources", typeof(DataSetResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dataset &apos;{0}&apos; is already exist.
        /// </summary>
        internal static string DataSet_0_IsAlreadyExist {
            get {
                return ResourceManager.GetString("DataSet_0_IsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dataset &apos;{0}&apos; is not found.
        /// </summary>
        internal static string DataSet_0_IsNotFound {
            get {
                return ResourceManager.GetString("DataSet_0_IsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dataset not allowed to delete because of depending service(s)!.
        /// </summary>
        internal static string DataSetNotAllowedToDeleteBecauseOfDependingService {
            get {
                return ResourceManager.GetString("DataSetNotAllowedToDeleteBecauseOfDependingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The operarion is not allowed, because the dataset &apos;{0}&apos; is busy!.
        /// </summary>
        internal static string Operation_is_not_allowed_the_dataset_0_is_busy {
            get {
                return ResourceManager.GetString("Operation_is_not_allowed_the_dataset_0_is_busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SampleDocument is empty.
        /// </summary>
        internal static string SampleDocumentIsEmpty {
            get {
                return ResourceManager.GetString("SampleDocumentIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Schema is empty.
        /// </summary>
        internal static string SchemaIsEmpty {
            get {
                return ResourceManager.GetString("SchemaIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The dataset name must be minimum {0} and maximum {1} characters.
        /// </summary>
        internal static string The_Dataset_name_MustBeMin_0_Max_1 {
            get {
                return ResourceManager.GetString("The_Dataset_name_MustBeMin_0_Max_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The dataset name  must match the regular expression: &apos;{0}&apos;.
        /// </summary>
        internal static string The_Dataset_name_MustMatchRegex_0 {
            get {
                return ResourceManager.GetString("The_Dataset_name_MustMatchRegex_0", resourceCulture);
            }
        }
    }
}
