//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.42000
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slamby.API.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DocumentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal DocumentResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Slamby.API.Resources.DocumentResources", typeof(DocumentResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Document with Id &apos;{0}&apos; does not found.
        /// </summary>
        internal static string DocumentWithId_0_DoesNotFound {
            get {
                return ResourceManager.GetString("DocumentWithId_0_DoesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Document with Id &apos;{0}&apos; is already exist.
        /// </summary>
        internal static string DocumentWithId_0_IsAlreadyExist {
            get {
                return ResourceManager.GetString("DocumentWithId_0_IsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Empty Id list specified.
        /// </summary>
        internal static string EmptyIdListSpecified {
            get {
                return ResourceManager.GetString("EmptyIdListSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error during indexing documents. Returning document id validation fails..
        /// </summary>
        internal static string ErrorDuringIndexingDocuments {
            get {
                return ResourceManager.GetString("ErrorDuringIndexingDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to FilterSettings or scrollId parameter must has value.
        /// </summary>
        internal static string FilterSettingsOrScrollIdParameterMustHasValue {
            get {
                return ResourceManager.GetString("FilterSettingsOrScrollIdParameterMustHasValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid document field: &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidDocumentField_0 {
            get {
                return ResourceManager.GetString("InvalidDocumentField_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid numeric filter value: {0}.
        /// </summary>
        internal static string InvalidNumericFilterValue {
            get {
                return ResourceManager.GetString("InvalidNumericFilterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Json schema validation error: {0}.
        /// </summary>
        internal static string JsonSchemaValidationError_0 {
            get {
                return ResourceManager.GetString("JsonSchemaValidationError_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Only field of primitive type is allowed for OrderByField.
        /// </summary>
        internal static string OnlyFieldOfPrimitiveTypeIsAllowedForOrderByField {
            get {
                return ResourceManager.GetString("OnlyFieldOfPrimitiveTypeIsAllowedForOrderByField", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; array has no items.
        /// </summary>
        internal static string The_0_Field_1_ArrayHasNoItems {
            get {
                return ResourceManager.GetString("The_0_Field_1_ArrayHasNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; array item has no content.
        /// </summary>
        internal static string The_0_Field_1_ArrayItemIsHasNoContent {
            get {
                return ResourceManager.GetString("The_0_Field_1_ArrayItemIsHasNoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; array item is not an integer.
        /// </summary>
        internal static string The_0_Field_1_ArrayItemIsNotInteger {
            get {
                return ResourceManager.GetString("The_0_Field_1_ArrayItemIsNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; array item is not a string or integer.
        /// </summary>
        internal static string The_0_Field_1_ArrayItemIsNotSimpleType {
            get {
                return ResourceManager.GetString("The_0_Field_1_ArrayItemIsNotSimpleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; has no content.
        /// </summary>
        internal static string The_0_Field_1_HasNoContent {
            get {
                return ResourceManager.GetString("The_0_Field_1_HasNoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; is an object type.
        /// </summary>
        internal static string The_0_Field_1_IsAnObjectType {
            get {
                return ResourceManager.GetString("The_0_Field_1_IsAnObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; is not Base64.
        /// </summary>
        internal static string The_0_Field_1_IsNotBase64 {
            get {
                return ResourceManager.GetString("The_0_Field_1_IsNotBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; is not found.
        /// </summary>
        internal static string The_0_Field_1_IsNotFound {
            get {
                return ResourceManager.GetString("The_0_Field_1_IsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; is not an integer.
        /// </summary>
        internal static string The_0_Field_1_IsNotInteger {
            get {
                return ResourceManager.GetString("The_0_Field_1_IsNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; is not a string or integer.
        /// </summary>
        internal static string The_0_Field_1_IsNotSimpleType {
            get {
                return ResourceManager.GetString("The_0_Field_1_IsNotSimpleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; is not a string.
        /// </summary>
        internal static string The_0_Field_1_IsNotString {
            get {
                return ResourceManager.GetString("The_0_Field_1_IsNotString", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; must be minimum {2} and maximum {3} characters.
        /// </summary>
        internal static string The_0_Field_1_MustBeMin_2_Max_3 {
            get {
                return ResourceManager.GetString("The_0_Field_1_MustBeMin_2_Max_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; must match the regular expression: &apos;{2}&apos;.
        /// </summary>
        internal static string The_0_Field_1_MustMatchRegex_2 {
            get {
                return ResourceManager.GetString("The_0_Field_1_MustMatchRegex_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The &apos;{0}&apos; field is missing.
        /// </summary>
        internal static string The_0_FieldIsMissing {
            get {
                return ResourceManager.GetString("The_0_FieldIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tag field is defined as an array type but this tag field is a simple type.
        /// </summary>
        internal static string TheFieldIsDefinedAsArrayButItIsSimpleType {
            get {
                return ResourceManager.GetString("TheFieldIsDefinedAsArrayButItIsSimpleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tag field is defined as a simple type but this tag field is an array type.
        /// </summary>
        internal static string TheFieldIsDefinedAsSimpleTypeButItIsArray {
            get {
                return ResourceManager.GetString("TheFieldIsDefinedAsSimpleTypeButItIsArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Valid sample size or percent is required.
        /// </summary>
        internal static string ValidSampleSizeOrPercentIsRequired {
            get {
                return ResourceManager.GetString("ValidSampleSizeOrPercentIsRequired", resourceCulture);
            }
        }
    }
}
