//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slamby.API.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DocumentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal DocumentResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Slamby.API.Resources.DocumentResources", typeof(DocumentResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Copying {0} documents from the {1} dataset to the {2} dataset.
        /// </summary>
        public static string Copy_0_Documents_From_1_To_2 {
            get {
                return ResourceManager.GetString("Copy_0_Documents_From_1_To_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Copy from the {0} dataset to the {1} dataset finished. {2} documents succeeded, {3} documents failed!.
        /// </summary>
        public static string CopyFinishedFrom_0_To_1_Succeeded_2_Failed_3 {
            get {
                return ResourceManager.GetString("CopyFinishedFrom_0_To_1_Succeeded_2_Failed_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Document with Id &apos;{0}&apos; does not found.
        /// </summary>
        public static string DocumentWithId_0_DoesNotFound {
            get {
                return ResourceManager.GetString("DocumentWithId_0_DoesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Document with Id &apos;{0}&apos; is already exist.
        /// </summary>
        public static string DocumentWithId_0_IsAlreadyExist {
            get {
                return ResourceManager.GetString("DocumentWithId_0_IsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Empty Id list specified.
        /// </summary>
        public static string EmptyIdListSpecified {
            get {
                return ResourceManager.GetString("EmptyIdListSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error during indexing documents. Returning document id validation fails..
        /// </summary>
        public static string ErrorDuringIndexingDocuments {
            get {
                return ResourceManager.GetString("ErrorDuringIndexingDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to FilterSettings or scrollId parameter must has value.
        /// </summary>
        public static string FilterSettingsOrScrollIdParameterMustHasValue {
            get {
                return ResourceManager.GetString("FilterSettingsOrScrollIdParameterMustHasValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid document field: &apos;{0}&apos;.
        /// </summary>
        public static string InvalidDocumentField_0 {
            get {
                return ResourceManager.GetString("InvalidDocumentField_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid numeric filter value: {0}.
        /// </summary>
        public static string InvalidNumericFilterValue {
            get {
                return ResourceManager.GetString("InvalidNumericFilterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Json schema validation error: {0}.
        /// </summary>
        public static string JsonSchemaValidationError_0 {
            get {
                return ResourceManager.GetString("JsonSchemaValidationError_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Moving {0} documents from the {1} dataset to the {2} dataset.
        /// </summary>
        public static string Move_0_Documents_From_1_To_2 {
            get {
                return ResourceManager.GetString("Move_0_Documents_From_1_To_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Move from the {0} dataset to the {1} dataset finished. {2} documents succeeded, {3} documents failed!.
        /// </summary>
        public static string MoveFinishedFrom_0_To_1_Succeeded_2_Failed_3 {
            get {
                return ResourceManager.GetString("MoveFinishedFrom_0_To_1_Succeeded_2_Failed_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Only field of primitive type is allowed for {0}.
        /// </summary>
        public static string OnlyFieldOfPrimitiveTypeIsAllowedFor_0 {
            get {
                return ResourceManager.GetString("OnlyFieldOfPrimitiveTypeIsAllowedFor_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The result file can be download from here: {0}.
        /// </summary>
        public static string ResultFileCanBeDownloadFromHere_0 {
            get {
                return ResourceManager.GetString("ResultFileCanBeDownloadFromHere_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; array has no items.
        /// </summary>
        public static string The_0_Field_1_ArrayHasNoItems {
            get {
                return ResourceManager.GetString("The_0_Field_1_ArrayHasNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; array item has no content.
        /// </summary>
        public static string The_0_Field_1_ArrayItemIsHasNoContent {
            get {
                return ResourceManager.GetString("The_0_Field_1_ArrayItemIsHasNoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; array item is not an integer.
        /// </summary>
        public static string The_0_Field_1_ArrayItemIsNotInteger {
            get {
                return ResourceManager.GetString("The_0_Field_1_ArrayItemIsNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; array item is not a string or integer.
        /// </summary>
        public static string The_0_Field_1_ArrayItemIsNotSimpleType {
            get {
                return ResourceManager.GetString("The_0_Field_1_ArrayItemIsNotSimpleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; has no content.
        /// </summary>
        public static string The_0_Field_1_HasNoContent {
            get {
                return ResourceManager.GetString("The_0_Field_1_HasNoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; is an object type.
        /// </summary>
        public static string The_0_Field_1_IsAnObjectType {
            get {
                return ResourceManager.GetString("The_0_Field_1_IsAnObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; is not Base64.
        /// </summary>
        public static string The_0_Field_1_IsNotBase64 {
            get {
                return ResourceManager.GetString("The_0_Field_1_IsNotBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; is not found.
        /// </summary>
        public static string The_0_Field_1_IsNotFound {
            get {
                return ResourceManager.GetString("The_0_Field_1_IsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; is not an integer.
        /// </summary>
        public static string The_0_Field_1_IsNotInteger {
            get {
                return ResourceManager.GetString("The_0_Field_1_IsNotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; is not a string or integer.
        /// </summary>
        public static string The_0_Field_1_IsNotSimpleType {
            get {
                return ResourceManager.GetString("The_0_Field_1_IsNotSimpleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; is not a string.
        /// </summary>
        public static string The_0_Field_1_IsNotString {
            get {
                return ResourceManager.GetString("The_0_Field_1_IsNotString", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; must be minimum {2} and maximum {3} characters.
        /// </summary>
        public static string The_0_Field_1_MustBeMin_2_Max_3 {
            get {
                return ResourceManager.GetString("The_0_Field_1_MustBeMin_2_Max_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The {0} field &apos;{1}&apos; must match the regular expression: &apos;{2}&apos;.
        /// </summary>
        public static string The_0_Field_1_MustMatchRegex_2 {
            get {
                return ResourceManager.GetString("The_0_Field_1_MustMatchRegex_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The &apos;{0}&apos; field is missing.
        /// </summary>
        public static string The_0_FieldIsMissing {
            get {
                return ResourceManager.GetString("The_0_FieldIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tag field is defined as an array type but this tag field is a simple type.
        /// </summary>
        public static string TheFieldIsDefinedAsArrayButItIsSimpleType {
            get {
                return ResourceManager.GetString("TheFieldIsDefinedAsArrayButItIsSimpleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tag field is defined as a simple type but this tag field is an array type.
        /// </summary>
        public static string TheFieldIsDefinedAsSimpleTypeButItIsArray {
            get {
                return ResourceManager.GetString("TheFieldIsDefinedAsSimpleTypeButItIsArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Valid sample size or percent is required.
        /// </summary>
        public static string ValidSampleSizeOrPercentIsRequired {
            get {
                return ResourceManager.GetString("ValidSampleSizeOrPercentIsRequired", resourceCulture);
            }
        }
    }
}
