//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:4.0.30319.42000
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slamby.API.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal GlobalResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Slamby.API.Resources.GlobalResources", typeof(GlobalResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to HTTP Header Content-Length is not set.
        /// </summary>
        internal static string ContentLengthIsNotSet {
            get {
                return ResourceManager.GetString("ContentLengthIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to DataSet &apos;{0}&apos; not found!.
        /// </summary>
        internal static string DataSet_0_NotFound {
            get {
                return ResourceManager.GetString("DataSet_0_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Missing &apos;{0}&apos; header!.
        /// </summary>
        internal static string Missing_0_Header {
            get {
                return ResourceManager.GetString("Missing_0_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to .
        /// </summary>
        internal static string NGramList {
            get {
                return ResourceManager.GetString("NGramList", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to NGram list contains duplicate values.
        /// </summary>
        internal static string NGramListContainsDuplicates {
            get {
                return ResourceManager.GetString("NGramListContainsDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to NGram list is empty.
        /// </summary>
        internal static string NGramListIsEmpty {
            get {
                return ResourceManager.GetString("NGramListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to NGram values should be between 1 and 6.
        /// </summary>
        internal static string NGramValuesShouldBeBetween1And6 {
            get {
                return ResourceManager.GetString("NGramValuesShouldBeBetween1And6", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Server resource error. Request entity is too large. Maximum value according to the server resources is {0} bytes.
        /// </summary>
        internal static string Request_Is_Too_Large_0 {
            get {
                return ResourceManager.GetString("Request_Is_Too_Large_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SDK {0} &lt;--&gt; API {1} version mismatch.
        /// </summary>
        internal static string SdkApiVersionMismatch {
            get {
                return ResourceManager.GetString("SdkApiVersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The argument {0} is not {1} type.
        /// </summary>
        internal static string TheArgument_0_IsNot_1_Type {
            get {
                return ResourceManager.GetString("TheArgument_0_IsNot_1_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The argument cannot be null: {0}.
        /// </summary>
        internal static string TheArgumentCannotBeNull_0 {
            get {
                return ResourceManager.GetString("TheArgumentCannotBeNull_0", resourceCulture);
            }
        }
    }
}
