//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Slamby.API.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ServiceResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Slamby.API.Resources.ServiceResources", typeof(ServiceResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Activating {0} service {1}.
        /// </summary>
        public static string Activating_0_Service_1 {
            get {
                return ResourceManager.GetString("Activating_0_Service_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to DataSet &apos;{0}&apos; not found!.
        /// </summary>
        public static string DataSet_0_NotFound {
            get {
                return ResourceManager.GetString("DataSet_0_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Empty Activate Settings! You have to use Activate Settings at least for the first Activation!.
        /// </summary>
        public static string EmptyActivateSettings {
            get {
                return ResourceManager.GetString("EmptyActivateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Export file can be download from here: {0}.
        /// </summary>
        public static string ExportFileCanBeDownloadFromHere_0 {
            get {
                return ResourceManager.GetString("ExportFileCanBeDownloadFromHere_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Exporting dictionaries from {0} service {1}.
        /// </summary>
        public static string ExportingDictionariesFrom_0_Service_1 {
            get {
                return ResourceManager.GetString("ExportingDictionariesFrom_0_Service_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Id can&apos;t be empty in the {0} Settings!.
        /// </summary>
        public static string IdCantBeEmptyIn_0_Settings {
            get {
                return ResourceManager.GetString("IdCantBeEmptyIn_0_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Indexing {0} service {1}.
        /// </summary>
        public static string Indexing_0_Service_1 {
            get {
                return ResourceManager.GetString("Indexing_0_Service_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to IndexPartial can be called after calling Index!.
        /// </summary>
        public static string IndexPartialCanBeCalledAfterCallingIndex {
            get {
                return ResourceManager.GetString("IndexPartialCanBeCalledAfterCallingIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid Id! Not existing Service!.
        /// </summary>
        public static string InvalidIdNotExistingService {
            get {
                return ResourceManager.GetString("InvalidIdNotExistingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid Service type! Only &apos;{0}&apos; Services are valid for this request!.
        /// </summary>
        public static string InvalidServiceTypeOnly_0_ServicesAreValidForThisRequest {
            get {
                return ResourceManager.GetString("InvalidServiceTypeOnly_0_ServicesAreValidForThisRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid Status! Only the Services with &apos;Active&apos; status can be deactivated!.
        /// </summary>
        public static string InvalidStatusOnlyTheServicesWithActiveStatusCanBeDeactivated {
            get {
                return ResourceManager.GetString("InvalidStatusOnlyTheServicesWithActiveStatusCanBeDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid Status! Only the Services with &apos;Active&apos; status can be indexed!.
        /// </summary>
        public static string InvalidStatusOnlyTheServicesWithActiveStatusCanBeIndexed {
            get {
                return ResourceManager.GetString("InvalidStatusOnlyTheServicesWithActiveStatusCanBeIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid Status! Only the Services with &apos;New&apos; status can be prepared!.
        /// </summary>
        public static string InvalidStatusOnlyTheServicesWithNewStatusCanBePrepared {
            get {
                return ResourceManager.GetString("InvalidStatusOnlyTheServicesWithNewStatusCanBePrepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid Status! Only the Services with &apos;Prepared&apos; or &apos;Active&apos; status can be exported!.
        /// </summary>
        public static string InvalidStatusOnlyTheServicesWithPreparedOrActiveStatusCanBeExported {
            get {
                return ResourceManager.GetString("InvalidStatusOnlyTheServicesWithPreparedOrActiveStatusCanBeExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid Status! Only the Services with &apos;Prepared&apos; status can be activated!.
        /// </summary>
        public static string InvalidStatusOnlyTheServicesWithPreparedStatusCanBeActivated {
            get {
                return ResourceManager.GetString("InvalidStatusOnlyTheServicesWithPreparedStatusCanBeActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to NGram can&apos;t be larger than the NGramCount of the DataSet!.
        /// </summary>
        public static string NGramCantBeLargerThanTheNGramCountOfTheDataSet {
            get {
                return ResourceManager.GetString("NGramCantBeLargerThanTheNGramCountOfTheDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to NGram count wasn&apos;t prepared!.
        /// </summary>
        public static string NGramCountWasntPrepared {
            get {
                return ResourceManager.GetString("NGramCountWasntPrepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to NGramList can&apos;t be empty!.
        /// </summary>
        public static string NGramListCantBeEmpty {
            get {
                return ResourceManager.GetString("NGramListCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to There is at least one parent tag in the ParentTagIdList which is not a parent of any activated tags!.
        /// </summary>
        public static string NotAllParentTagExists {
            get {
                return ResourceManager.GetString("NotAllParentTagExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The server doesn&apos;t have enough resource to activate the service with the given settings!.
        /// </summary>
        public static string NotEnoughResourceToActivateService {
            get {
                return ResourceManager.GetString("NotEnoughResourceToActivateService", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The operation is not allowed, because the service &apos;{0}&apos; is busy!.
        /// </summary>
        public static string Operation_is_not_allowed_the_Service_0_is_busy {
            get {
                return ResourceManager.GetString("Operation_is_not_allowed_the_Service_0_is_busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Partial indexing {0} service {1}.
        /// </summary>
        public static string PartialIndexing_0_Service_1 {
            get {
                return ResourceManager.GetString("PartialIndexing_0_Service_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Preparing {0} service {1}.
        /// </summary>
        public static string Preparing_0_Service_1 {
            get {
                return ResourceManager.GetString("Preparing_0_Service_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} Service not exists or not activated!.
        /// </summary>
        public static string ServiceNotExistsOrNotActivated {
            get {
                return ResourceManager.GetString("ServiceNotExistsOrNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Successfully activated {0} service {1}!.
        /// </summary>
        public static string SuccessfullyActivated_0_Service_1 {
            get {
                return ResourceManager.GetString("SuccessfullyActivated_0_Service_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Successfully exported dictionaries from {0} service {1}!.
        /// </summary>
        public static string SuccessfullyExportedDictionariesFrom_0_Service_1 {
            get {
                return ResourceManager.GetString("SuccessfullyExportedDictionariesFrom_0_Service_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Successfully indexed {0} service {1}!.
        /// </summary>
        public static string SuccessfullyIndexed_0_Service_1 {
            get {
                return ResourceManager.GetString("SuccessfullyIndexed_0_Service_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Successfully partial indexed {0} service {1}!.
        /// </summary>
        public static string SuccessfullyPartialIndexed_0_Service_1 {
            get {
                return ResourceManager.GetString("SuccessfullyPartialIndexed_0_Service_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Successfully prepared {0} service {1}!.
        /// </summary>
        public static string SuccessfullyPrepared_0_Service_1 {
            get {
                return ResourceManager.GetString("SuccessfullyPrepared_0_Service_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The following EmphasizedTagIds were not prepared: {0}.
        /// </summary>
        public static string TheFollowingEmphasizedTagIdsWereNotPrepared_0 {
            get {
                return ResourceManager.GetString("TheFollowingEmphasizedTagIdsWereNotPrepared_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The following Fields not exist in the SampleDocument: {0}.
        /// </summary>
        public static string TheFollowingFieldsNotExistInTheSampleDocument_0 {
            get {
                return ResourceManager.GetString("TheFollowingFieldsNotExistInTheSampleDocument_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The following NGrams not exist in the Services: {0}.
        /// </summary>
        public static string TheFollowingNGramsNotExistInTheService_0 {
            get {
                return ResourceManager.GetString("TheFollowingNGramsNotExistInTheService_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The following TagIds not exist in the DataSet: {0}.
        /// </summary>
        public static string TheFollowingTagIdsNotExistInTheDataSet_0 {
            get {
                return ResourceManager.GetString("TheFollowingTagIdsNotExistInTheDataSet_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The following TagIds not exist in the Service: {0}.
        /// </summary>
        public static string TheFollowingTagIdsNotExistInTheService_0 {
            get {
                return ResourceManager.GetString("TheFollowingTagIdsNotExistInTheService_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The following TagIds were not prepared: {0}.
        /// </summary>
        public static string TheFollowingTagIdsWereNotPrepared_0 {
            get {
                return ResourceManager.GetString("TheFollowingTagIdsWereNotPrepared_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The given tag has no words in dictionary!.
        /// </summary>
        public static string TheGivenTagHasNoWordsInDictionary {
            get {
                return ResourceManager.GetString("TheGivenTagHasNoWordsInDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The given tag is missing from the PRC Service!.
        /// </summary>
        public static string TheGivenTagIsMissingFromThePRCService {
            get {
                return ResourceManager.GetString("TheGivenTagIsMissingFromThePRCService", resourceCulture);
            }
        }
    }
}
